### ISSUE TITLE
Could you make it clearer what a "selector on the file's scope" is?

### ISSUE THREAD

**Issue by makoConstruct** [guillermooo/sublime-undocs#69] opened 2014-09-04 21:54 UTC
No idea why source.python means anything to sublime, nor how to provide more specific selectors, a link to a full explanation[another doc page?] would be do well here.

**Comment by FichteFoll** [comment] 2014-09-04 22:16
Thanks for your concern, we will consider this. I also believe that scopes and selectors, a very core part of ST/TM, are not covered enough currently.

**Comment by FichteFoll** [comment] 2014-12-06 13:03
Closing this as a duplicate of #101 (I know this issue is older but the other one has more details).

**Closed as completed by FichteFoll** 2014-12-06 13:03 UTC
Labels: duplicate
